Rails:
    Enabled: true
AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - spec/factories/*
    - script/collectd/**/*
    - config/initializers/secret_token.rb
    - config/application.rb
    - vendor/bundle/**/*
    - bin/**/*
    - tmp/**/*
    - Rakefile
    - Gemfile
    - lib/tasks/auto_annotate_models.rake
