language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
bundler_args: --without production
cache: bundler
services:
  - mysql
before_script:
  - mysql -e 'create database albin_auth_test;'
addons:
  code_climate:
    repo_token: a2cc334f7ed4701aaac111609b85b1c087afd4eab46bc1d9d5ace8d4621f1fc9
env:
- TEST_ENV_TRAVIS=true